server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


## ??MyBatis-Plus?????? ??sql
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true # ?????????role_id ? roleId?
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??SQL????????